[project]
name = "ctp-swig-build"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "meson-python>=0.18.0",
    "mypy>=1.18.1",
]
